import org.gradle.internal.jvm.Jvm
import org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension
import org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
  dependencies {
    classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0'
    classpath 'com.diffplug.spotless:spotless-plugin-gradle:7.0.2'
    classpath 'org.jetbrains.dokka:dokka-gradle-plugin:2.0.0'
    classpath 'ru.vyarus:gradle-animalsniffer-plugin:2.0.0'
    classpath 'com.vanniktech:gradle-maven-publish-plugin:0.30.0'
  }

  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}

apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'com.vanniktech.maven.publish'

kotlin {
  androidNativeArm32()
  androidNativeArm64()
  androidNativeX86()
  androidNativeX64()
  iosArm64()
  iosX64()
  iosSimulatorArm64()
  js().nodejs()
  jvm()
  linuxArm64()
  linuxX64()
  macosX64()
  macosArm64()
  mingwX64()
  tvosArm64()
  tvosX64()
  tvosSimulatorArm64()
  wasmJs().nodejs()
  wasmWasi().nodejs()
  watchosArm32()
  watchosArm64()
  watchosDeviceArm64()
  watchosX64()
  watchosSimulatorArm64()

  sourceSets {
    commonTest {
      dependencies {
        implementation 'org.jetbrains.kotlin:kotlin-test'
      }
    }
  }
}

repositories {
  mavenCentral()
}

apply plugin: 'com.diffplug.spotless'
spotless {
  kotlin {
    ktlint().editorConfigOverride([
      'ktlint_standard_filename': 'disabled',
    ])
  }
}

tasks.withType(KotlinCompile).configureEach {
  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_1_8.toString()
    freeCompilerArgs += [
        '-progressive',
        '-Xjvm-default=all',
    ]
  }
}

tasks.withType(JavaCompile).configureEach {
  sourceCompatibility = JavaVersion.VERSION_1_8.toString()
  targetCompatibility = JavaVersion.VERSION_1_8.toString()
}

apply plugin: 'ru.vyarus.animalsniffer'

dependencies {
  signature 'org.codehaus.mojo.signature:java18:1.0@signature'
  signature 'net.sf.androidscents.signature:android-api-level-21:5.0.1_r2@signature'
}
